#!/usr/bin/env ruby

def exe_cmd(cmd)
  puts cmd
  system cmd
end

cmd = "git add ."
exe_cmd cmd

args = ARGV.join(' ')
cmd = "git commit . -m '#{ARGV[0]}'"
exe_cmd cmd

cmd = "git push origin master"
exe_cmd cmd

